### ISSUE TITLE
Issue tracker/contact information not listed on website

### ISSUE THREAD

**Issue by hodefoting** [libregraphicsmeeting/htdocs-2015#8]
When not finding links to this issue tracker on the website; I was instructed to file an issue in the issue tracker. Filing this issue would have been easier if it already was resolved.

**Comment by ms-studio** [comment]
Hi pippin, 

do you mean, we should add a link to this issue tracker to the Contacts page?  
http://libregraphicsmeeting.org/2015/contact/

**Comment by aoloe** [comment]
hi

i think that we should add it to the list all contact options on the lgm/ site.

for the 2015/contact site we can add it for people who want to report an issue with the site (as an alternative to the mailing list; there are (lot of? more and more?) people more comfortable with putting something on github rather than joining a mailing list...)

à propos 2015/contact and mailing list: we should ask ginger, if she really wanted to use the create list instead of the lgm one...

**Comment by ms-studio** [comment]
Ok, so I added a link to the English and French contact page:
http://libregraphicsmeeting.org/2015/contact/
